name: ci

on:
  push:

jobs:
  verify:
    name: verify build
    uses: ./.github/workflows/verify.yaml
    
  publish:
    name: publish package
    runs-on: ubuntu-latest
    needs: [ verify ]
    if: ${{ contains(fromJSON('["refs/heads/main", "refs/heads/development"]'), github.ref) }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - uses: s4u/maven-settings-action@v2.8.0
      with:
        servers: ${{ secrets.NEXUS_REGISTRY}}
    - run: mvn clean deploy -Dmaven.test.skip=true

