name: ci

on:
  push:

jobs:
  verify:
    name: verify build
    uses: ./.github/workflows/verify.yaml
    
  publish:
    name: publish package
    runs-on: ubuntu-latest
    needs: [ verify ]
    permissions:
      contents: read
      packages: write
    if: ${{ contains(fromJSON('["refs/heads/main", "refs/heads/development"]'), github.ref) }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: publish package
      run: mvn clean deploy -Dmaven.test.skip=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}