name: ci

on:
  push:

jobs:
  verify:
    name: verify build
    uses: ./.github/workflows/verify.yaml
  publish:
    name: publish package
    runs-on: ubuntu-latest
    needs: [ verify ]
    permissions:
      contents: write
      packages: write
    if: ${{ contains(fromJSON('["refs/heads/release", "refs/heads/snapshot"]'), github.ref) }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: bump version
      id: bump
      uses: nnichols/maven-version-bump-action@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: print version
      run: "echo 'New Version: ${{steps.bump.outputs.version}}'"
    - name: publish package
      uses: s4u/maven-settings-action@v2.8.0
      with:
        servers: ${{ secrets.AZURE_MAVEN}}
    - run: mvn clean deploy -Dmaven.test.skip=true
